### PR TITLE
bug/112 pt_BR

### PR DESCRIPTION
**Pull request by ginglass**
Corrige issue #112 para indicar opcional atributos que não fazem sentido para instituições que só tratam PF.
Pessoal, mantive a proposta do PR #120 aberto pelo @RalphBragg, mas questiono sobre a opcionalidade da claim CPF, pois entendo que essa não deveria ser opcional.

Fix Bug #112 .  @GislaineAlmeida, @DeiGratia33 and @alex-siqueira would you please check my comment at #120 ? As we always have a person authenticatiing aganst ASPSP system and giving his consent to share data, even when he selected a business account (assuming UX is going to give some option to a user select an especific account), at the end, we always have a CPF that should be related to an account / authentication, right @GislaineAlmeida @alex-siqueira ? If it is true, we have to keep line 4 as it was originally.

### CODE REVIEW

**Comment by DeiGratia33** [comment]
I believe Mario identified something essential here. As he described, even using a business account with CNPJ, the authentication is always performed by a human, a role that will have a CPF. 

IMHO
This way the ASPSP, when receiving the consent request for a business account, it should be sent along with the CPF, and the validation done by ASPSP will check if the CPF sent by TPP has access to the CNPJ. The thins is, the CPF will need to be registered and authorized at the ASPSP prior to request the access using a TPP.

The CNPJ claim is optional, but the CPF is always mandatory.

**Comment by RalphBragg** [comment]
I personally agree with @DeiGratia33. Encouraging people to give away a CPF to a TPP is good enough to prove that the Customer has a relationship with the TPP. Asking the customers to then share multiple CNPJs and then to go through multiple consent journeys one for each CNPJ would sub optimal. 

It would be good to see the UI/UX and wireframes that the customer experience team has on this.

**Comment by GislaineAlmeida** [comment]
> I believe Mario identified something essential here. As he described, even using a business account with CNPJ, the authentication is always performed by a human, a role that will have a CPF.
> 
> IMHO
> This way the ASPSP, when receiving the consent request for a business account, it should be sent along with the CPF, and the validation done by ASPSP will check if the CPF sent by TPP has access to the CNPJ. The thins is, the CPF will need to be registered and authorized at the ASPSP prior to request the access using a TPP.
> 
> The CNPJ claim is optional, but the CPF is always mandatory.

Hi,
I understand that the CPF is always mandatory and yes, the ASPSP needs to check if it is related to that specific CNPJ (an authorized operator for example). After verification, it may generate an error message and interrupt the journey, if the CPF is not really authorized. Do you know if we have this scenario mapped by UX? @mpivaa Do you know anything?

**Review by mdjunior — APPROVED** [review]

**Comment by RalphBragg** [comment]
Hi - given that the OIDF is writing these tests can someone propose a PR for the english vesion of the specification please?

**Pull request merged**
