### PR TITLE
Fix field software_jwks_endpoint in SSA example

### PR DESCRIPTION
**Pull request by dobau**

### CODE REVIEW

**Review by RalphBragg — COMMENTED** [review]
The correct property is URI and this has been addressed in sandbox.

eyJraWQiOiJzaWduZXIiLCJ0eXAiOiJKV1QiLCJhbGciOiJQUzI1NiJ9.eyJzb2Z0d2FyZV9qd2tzX2luYWN0aXZlX3VyaSI6Imh0dHBzOlwvXC9rZXlzdG9yZS5zYW5kYm94LmRpcmVjdG9yeS5vcGVuYmFua2luZ2JyYXNpbC5vcmcuYnJcLzc0ZTkyOWQ5LTMzYjYtNGQ4NS04YmE3LWMxNDZjODY3YTgxN1wvYjg5ODZhNDMtZTczMC00NjBmLTk3ZjktOWFkOTBmNGUzMWQzXC9pbmFjdGl2ZVwvYXBwbGljYXRpb24uandrcyIsInNvZnR3YXJlX21vZGUiOiJMaXZlIiwic29mdHdhcmVfcmVkaXJlY3RfdXJpcyI6WyJodHRwczpcL1wvb2F1dGgucHN0bW4uaW9cL3YxXC9jYWxsYmFjayJdLCJzb2Z0d2FyZV9zdGF0ZW1lbnRfcm9sZXMiOltdLCJzb2Z0d2FyZV9jbGllbnRfbmFtZSI6Ik1vY2sgQmFuayBDbGllbnQgMSIsIm9yZ19zdGF0dXMiOiJBY3RpdmUiLCJzb2Z0d2FyZV9jbGllbnRfaWQiOiJOcUt6OS1BX0xpdkFJT0FqSHlYcEwiLCJpc3MiOiJPcGVuIEJhbmtpbmcgT3BlbiBCYW5raW5nIEJyYXNpbCBzYW5kYm94IFNTQSBpc3N1ZXIiLCJzb2Z0d2FyZV90b3NfdXJpIjoiaHR0cHM6XC9cL3d3dy5yYWlkaWFtLmNvbSIsInNvZnR3YXJlX2p3a3NfdHJhbnNwb3J0X2luYWN0aXZlX3VyaSI6Imh0dHBzOlwvXC9rZXlzdG9yZS5zYW5kYm94LmRpcmVjdG9yeS5vcGVuYmFua2luZ2JyYXNpbC5vcmcuYnJcLzc0ZTkyOWQ5LTMzYjYtNGQ4NS04YmE3LWMxNDZjODY3YTgxN1wvYjg5ODZhNDMtZTczMC00NjBmLTk3ZjktOWFkOTBmNGUzMWQzXC9pbmFjdGl2ZVwvdHJhbnNwb3J0Lmp3a3MiLCJzb2Z0d2FyZV9wb2xpY3lfdXJpIjoiaHR0cHM6XC9cL3d3dy5yYWlkaWFtLmNvbSIsInNvZnR3YXJlX2lkIjoiYjg5ODZhNDMtZTczMC00NjBmLTk3ZjktOWFkOTBmNGUzMWQzIiwic29mdHdhcmVfandrc190cmFuc3BvcnRfdXJpIjoiaHR0cHM6XC9cL2tleXN0b3JlLnNhbmRib3guZGlyZWN0b3J5Lm9wZW5iYW5raW5nYnJhc2lsLm9yZy5iclwvNzRlOTI5ZDktMzNiNi00ZDg1LThiYTctYzE0NmM4NjdhODE3XC9iODk4NmE0My1lNzMwLTQ2MGYtOTdmOS05YWQ5MGY0ZTMxZDNcL3RyYW5zcG9ydC5qd2tzIiwic29mdHdhcmVfY2xpZW50X3VyaSI6Imh0dHBzOlwvXC93d3cucmFpZGlhbS5jb20iLCJzb2Z0d2FyZV9sb2dvX3VyaSI6Imh0dHBzOlwvXC93d3cucmFpZGlhbS5jb20iLCJvcmdfaWQiOiI3NGU5MjlkOS0zM2I2LTRkODUtOGJhNy1jMTQ2Yzg2N2E4MTciLCJzb2Z0d2FyZV9qd2tzX3VyaSI6Imh0dHBzOlwvXC9rZXlzdG9yZS5zYW5kYm94LmRpcmVjdG9yeS5vcGVuYmFua2luZ2JyYXNpbC5vcmcuYnJcLzc0ZTkyOWQ5LTMzYjYtNGQ4NS04YmE3LWMxNDZjODY3YTgxN1wvYjg5ODZhNDMtZTczMC00NjBmLTk3ZjktOWFkOTBmNGUzMWQzXC9hcHBsaWNhdGlvbi5qd2tzIiwic29mdHdhcmVfZW52aXJvbm1lbnQiOiJQcm9kdWN0aW9uIiwic29mdHdhcmVfdmVyc2lvbiI6IjEuMDAiLCJzb2Z0d2FyZV9yb2xlcyI6W10sIm9yZ19uYW1lIjoiT3BlbiBCYW5raW5nIEJyYXNpbCIsImlhdCI6MTYyMDkxNzAzMCwib3JnYW5pc2F0aW9uX2NvbXBldGVudF9hdXRob3JpdHlfY2xhaW1zIjpbeyJhdXRob3Jpc2F0aW9uX2RvbWFpbiI6Ik9wZW4gQmFua2luZyBCcmFzaWwgIiwiYXV0aG9yaXNhdGlvbnMiOlt7Im1lbWJlcl9zdGF0ZSI6IkJSIn1dLCJyZWdpc3RyYXRpb25faWQiOiJDTlBKLU9CQi1EQURPUyIsImF1dGhvcml0eV9pZCI6IjUzNjBkNWJmLTUwMjQtNDdjZC1iZDE4LWRhYWIwOGRmMzhiYSIsImF1dGhvcmlzYXRpb25fcm9sZSI6IkRBRE9TIiwiYXV0aG9yaXR5X2NvZGUiOiJCQ0IiLCJzdGF0dXMiOiJBY3RpdmUifSx7ImF1dGhvcmlzYXRpb25fZG9tYWluIjoiT3BlbiBCYW5raW5nIEJyYXNpbCAiLCJhdXRob3Jpc2F0aW9ucyI6W10sInJlZ2lzdHJhdGlvbl9pZCI6IkNOUEotT0JCLVBBR1RPIiwiYXV0aG9yaXR5X2lkIjoiNTM2MGQ1YmYtNTAyNC00N2NkLWJkMTgtZGFhYjA4ZGYzOGJhIiwiYXV0aG9yaXNhdGlvbl9yb2xlIjoiUEFHVE8iLCJhdXRob3JpdHlfY29kZSI6IkJDQiIsInN0YXR1cyI6IkFjdGl2ZSJ9LHsiYXV0aG9yaXNhdGlvbl9kb21haW4iOiJPcGVuIEJhbmtpbmcgQnJhc2lsICIsImF1dGhvcmlzYXRpb25zIjpbXSwicmVnaXN0cmF0aW9uX2lkIjoiVW5pcVJlZ2lzdHJhdGlvbklkIiwiYXV0aG9yaXR5X2lkIjoiNTM2MGQ1YmYtNTAyNC00N2NkLWJkMTgtZGFhYjA4ZGYzOGJhIiwiYXV0aG9yaXNhdGlvbl9yb2xlIjoiVFJEIiwiYXV0aG9yaXR5X2NvZGUiOiJCQ0IiLCJzdGF0dXMiOiJJbmFjdGl2ZSJ9XX0.pw-8yKCj9gCizyaO3vBF9dBXJHBIr2LF_UsTVIWMQ_YSjgSkwIJqXeiaRqVwH39IZCwxp7HBAXDBGlaauEOTwZ8ZOf959GAMLiUWQAtto5Ynnc1KRPRzVpyUtANjQCuRZwVisrH3mknvCloxcy7jkunK3f3ADidj3UKcOQ6ZQUkmgY6gnohU-a9ZHNi85d-bXi_VfQxdetd6hBaoo15Ppf2TLRxGPHabzK-8j2l-eIgQEf_3wMQeRvVM6Eo3MRpGSAG3pwpOCKL4ASv16phTWb9qJK2t0IcMCC50lueYcqN84yhe2ZwdYg3bANmoy8Qu4ubDPqbuyHeFPe5q1IJNTw

**Review by RalphBragg — CHANGES_REQUESTED** [review]
As per previous comment, the correct property is URI.

**Comment by dobau** [comment]
Hi Ralph, so is there a error here?

image

**Comment by RalphBragg** [comment]
Hi,

Yes there is. I will get it fixed.
Thanks for spotting it!

RB

________________________________

**Pull request closed without merging**
